name: CI - Next.js PNPM

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Récupération du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Installation de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # Installation de pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      # Vérification des versions
      - name: Check Node & PNPM versions
        run: |
          node -v
          pnpm -v

      # Installation des dépendances
      - name: Install dependencies
        run: pnpm install

      # Lint
      - name: Run lint
        run: pnpm lint

      # Build Next.js
      - name: Build application
        run: pnpm build
