name: CI-G.E

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #  Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      #  Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      #  Installer pnpm (AVANT le cache)
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      #  Vérifier les versions
      - name: Check Node & PNPM versions
        run: |
          node -v
          pnpm -v

      #  Cache pnpm
      - name: Setup pnpm cache
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      #  Installer les dépendances
      - name: Install dependencies
        run: pnpm install

      #  Lint
      - name: Run lint
        run: pnpm lint

      #  Build
      - name: Build application
        run: pnpm build
